name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - uses: actions/checkout@master
    - name: Compress action step
      uses: master-atul/tar-action@v1.0.2
      id: compress
      with:
        command: c
        files: |
          target/release/hwrust
        outPath: hwrust.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hwrust.tar.gz
        asset_name: hwrust
        tag: ${{ github.ref }}
        overwrite: true
