name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Compress action step
      uses: master-atul/tar-action@v1.0.2
      id: compress
      with:
        command: c
        files: |
          target/release/hwrust
        outPath: hwrust.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hwrust.tar.gz
        asset_name: hwrust.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
    - name: Update formula
      uses: mislav/bump-homebrew-formula-action@v1.6
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: "!contains(github.ref, '-')" # skip prereleases
      with:
        homebrew-tap: atmnk/homebrew-hwrust
        formula-name: hwrust
        download-url: 'https://github.com/atmnk/hwrust/releases/download/v{{version}}/hwrust.tar.gz'
        commit-message: 'chore: upgrade {{formulaName}} formula to v{{version}}'
